version: "3"
services:
  healthchecks:
    image: "healthchecks/healthchecks:v2.4.1"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.healthchecks.rule=Host(`healthchecks.bitraf.no`)"
      - "traefik.http.routers.healthchecks.entrypoints=websecure"
      - "traefik.http.routers.healthchecks.tls.certresolver=bitraf"
      - "traefik.http.services.myservice.loadbalancer.server.port=8000"
    environment:
      DEBUG: "False"
      DB: postgres
      DB_HOST: {{ db_host }}
      DB_PORT: {{ db_port }}
      DB_NAME: {{ db_database }}
      DB_USER: {{ db_username }}
      DB_PASSWORD: {{ db_password }}
      DB_SSLMODE: require
      DEFAULT_FROM_EMAIL: itavdelingen@bitraf.no
      SECRET_KEY: {{ secret_key }}
      EMAIL_HOST: bite.lan.bitraf.no
      EMAIL_PORT: 25
      EMAIL_USE_TLS: "False"
      SITE_LOGO_URL: "https://bitraf.no/wp-content/uploads/2021/05/cropped-bitraf-1-01a-02.png"
      SITE_NAME: "Bitraf checks"
      SITE_ROOT: "https://healthchecks.bitraf.no"

networks:
  traefik:
    external: true
