- become: yes
  become_user: postgres
  when: p2k16__ldap_state == 'present'
  tags:
    - p2k16
    - p2k16-ldap
  vars:
    ansible_ssh_pipelining: true
  block:
    - name: CREATE USER p2k16-ldap
      tags: update-password
      notify: p2k16 restart
      postgresql_user:
        name: p2k16-ldap
        password: "{{ p2k16_secret.db_password_ldap }}"
        encrypted: yes
    - name: GRANT p2k16-ldap
      postgresql_privs:
        database: p2k16
        privs: USAGE
        type: schema
        objs: public
        roles: p2k16-ldap

- become: yes
  become_user: postgres
  tags:
    - p2k16
    - p2k16-ldap
  vars:
    ansible_ssh_pipelining: true
  when: p2k16__ldap_state == 'absent'
  block:
    - name: DROP USER p2k16-ldap
      postgresql_user:
        name: p2k16-ldap
        state: absent
        db: p2k16
        priv: ALL

- become: yes
  tags:
    - p2k16
    - p2k16-ldap
  when: p2k16__ldap_state == 'present'
  block:
    - name: p2k16-ldap systemd unit
      copy:
        src: etc/systemd/system/p2k16-ldap@.service
        dest: /etc/systemd/system/p2k16-ldap@.service

    - name: enable p2k16-ldap systemd unit
      systemd:
        name: "p2k16-ldap@{{ p2k16.domain_name }}.service"
        daemon_reload: yes
        enabled: yes
        state: started

- become: yes
  tags:
    - p2k16
    - p2k16-ldap
  when: p2k16__ldap_state == 'absent'
  block:
    - name: disable p2k16-ldap systemd unit
      systemd:
        name: "p2k16-ldap@{{ p2k16.domain_name }}.service"
        daemon_reload: yes
        enabled: no
        state: stopped

    - name: p2k16-ldap systemd unit
      file:
        path: /etc/systemd/system/p2k16-ldap@.service
        state: absent
