---
- name: p2k16 nodejs
  become: yes
  tags: p2k16
  block:
    - name: packages
      apt:
        name: "{{ item }}"
        install_recommends: no
      with_items:
        - apt-transport-https

    - name: Install NodeSource key
      tags: packages
      apt_key:
        id: 1655a0ab68576280
        keyserver: keyserver.ubuntu.com

    - name: nodesource apt repository
      tags: packages
      notify: update apt cache
      copy:
        dest: /etc/apt/sources.list.d/nodesource.list
        content: 'deb https://deb.nodesource.com/node_8.x sid main'

- meta: flush_handlers

- name: accounts for p2k16
  become: yes
  tags: user
  block:
    - name: create p2k16 user
      user:
        name: p2k16
        shell: "/bin/false"
        createhome: no
        home: /
        system: yes

- name: www for p2k16
  become: yes
  tags: www
  vars:
    docroot: "var/www/{{ p2k16_domain_name }}"
  block:
    - name: Packages for www
      apt:
        name: "{{ item }}"
        install_recommends: no
      with_items:
        - nginx

    - name: no default nginx site
      notify: reload nginx
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: nginx config
      notify: reload nginx
      template:
        dest: "/etc/nginx/sites-enabled/{{ p2k16_domain_name }}"
        src: etc/nginx/sites-enabled/p2k16.j2

    - name: docroot dir
      file:
        path: "{{ docroot }}"
        state: directory

    - name: docroot dir
      copy:
        dest: "/{{ docroot }}/index.html"
        src: "{{ docroot }}/index.html"

- name: p2k16 database
  tags: p2k16-pg
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  block:
    - name: p2k16
      postgresql_user: 
        name: p2k16
        role_attr_flags: "NOLOGIN"
    - name: p2k16-flyway
      postgresql_user: 
        name: p2k16-flyway
    - name: p2k16-web
      postgresql_user: 
        name: p2k16-web
    - name: p2k16 db
      postgresql_db:
        name: "p2k16"
        encoding: "utf-8"
        owner: "p2k16"
    - postgresql_privs:
        database: p2k16
        state: present
        privs: USAGE
        type: schema
        objs: public
        roles: p2k16-web,p2k16-flyway

- name: p2k16 main
  become: yes
  tags:
    - p2k16
    - p2k16-main
  block:
    - name: p2k16 packages
      apt:
        name: "{{ item }}"
        install_recommends: no
      with_items:
        - python3
        - virtualenv
        - nodejs

    - name: p2k16 git
      notify: p2k16 restart
      git:
        repo: 'https://github.com/bitraf/p2k16'
        dest: /opt/p2k16/src
        version: master

    - name: p2k16 pip
      notify: p2k16 restart
      pip:
        name: /opt/p2k16/src/web
        virtualenv: /opt/p2k16/env
        virtualenv_python: python3
        extra_args: --trusted-host github.com --process-dependency-links

    - name: p2k16 install bower
      notify: p2k16 restart
      npm:
        path: /opt/p2k16
        name: bower
        global: no

    - name: p2k16 bower install
      notify: p2k16 restart
      bower:
        path: /opt/p2k16/src/web
        relative_execpath: /opt/p2k16/node_modules/.bin

    - name: /etc/p2k16
      tags: systemd
      file:
        path: /etc/p2k16
        state: directory

    - name: p2k16 config
      tags: systemd
      notify: p2k16 restart
      template:
        dest: "/etc/p2k16/{{ p2k16_domain_name }}.conf"
        src: etc/p2k16/environment.conf.j2

    - name: systemd unit
      tags: systemd
      copy:
        src: etc/systemd/system/p2k16@.service
        dest: /etc/systemd/system/p2k16@.service

    - name: enable systemd unit
      tags: systemd
      systemd:
        name: "p2k16@{{ p2k16_domain_name }}.service"
        daemon_reload: yes
        enabled: yes
        state: started
