version: "3"

services:
  p2k16:
    image: "{{ docker_image }}:{{ docker_tag }}"
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"

      - "traefik.http.middlewares.bitraf-internal.ipwhitelist.sourcerange=77.40.158.96/27, 10.13.37.0/24, 85.90.244.199"

      - "traefik.http.routers.p2k16-passwd.priority=0"
      - "traefik.http.routers.p2k16-passwd.rule=Host(`{{ '`, `'.join(p2k16_public_domains) }}`) && PathPrefix(`/passwd.php`)"
      - "traefik.http.routers.p2k16-passwd.entrypoints=websecure"
      - "traefik.http.routers.p2k16-passwd.tls.certresolver=bitraf"
      - "traefik.http.routers.p2k16-passwd.middlewares=bitraf-internal"

      - "traefik.http.routers.p2k16.priority=1"
      - "traefik.http.routers.p2k16.rule=Host(`{{ '`, `'.join(p2k16_public_domains) }}`)"
      - "traefik.http.routers.p2k16.entrypoints=websecure"
      - "traefik.http.routers.p2k16.tls.certresolver=bitraf"
    environment:
      DLOCK_BASE_URL: "{{ p2k16_dlock_base_url }}"
      DLOCK_USERNAME: "{{ p2k16_dlock_username }}"
      DLOCK_PASSWORD: "{{ bitraf_passwords.dlock[p2k16_dlock_username].password }}"
      P2K16_BIND: "0.0.0.0:5000"
      MQTT_HOST: "{{ p2k16_mqtt_host }}"
      MQTT_PORT: "{{ p2k16_mqtt_port }}"
      MQTT_USERNAME: "{{ p2k16_mqtt_username }}"
      MQTT_PASSWORD: "{{ bitraf_passwords.mqtt[p2k16_mqtt_username].password }}"
      MQTT_PREFIX: "{{ p2k16_mqtt_prefix }}"
      MQTT_PREFIX_TOOL: "{{ p2k16_mqtt_prefix_tool }}"
      MEMBERSHIP_CC: "{{ p2k16_membership_cc }}"
      LDAP_DB: "dbname={{ db_database }} user={{ db_web_username }} password={{ db_web_password }} host={{ db_host }} port={{ db_port }} sslmode=require"
      SQLALCHEMY_DATABASE_URI: "postgresql://{{ db_web_username }}:{{ db_web_password }}@{{ db_host }}:{{ db_port }}/{{ db_database }}?sslmode=require"
      SECRET_KEY: "{{ flask_secret_key }}"
      STRIPE_WEBHOOK_SECRET: "{{ stripe_webhook_secret }}"
      STRIPE_SECRET_KEY: "{{ stripe_secret_key }}"
      STRIPE_PUBLIC_KEY: "{{ stripe_public_key }}"
      SMTP_HOST: bite.lan.bitraf.no

networks:
  traefik:
    external: true
