version: "3"
services:
  hugo:
    # Remember to update .gitlab-ci.yml if you change this version
    image: jojomi/hugo:0.85.0
    restart: "unless-stopped"
    user: "1000:1000"
    ports:
      - "1313:1313"
    volumes:
      - ../../doc/resources:/src/resources
      - ../../doc:/src
      - ../../doc/output:/output
    command: /run.sh --cleanDestinationDir
    environment:
      HUGO_THEME: "docport"
      HUGO_WATCH: "true"
      HUGO_REFRESH_TIME: "1"
