users:
  - username: eliasbakken
    state: present
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEVoE61UreMtgITTsdSoX2UzBmeLJitKsXRhia7EmJP0
  - username: mastensg
    state: present
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICOayiImJKc7Qfmp2i33QNreBZ+zatorDVP3IUEPXlch mastensg@reed
