---
- become: yes
  tags: lusers
  vars:
    login_shell:
      Debian: "/bin/bash"
      OpenBSD: "/bin/sh"
    nologin_shell:
      Debian: "/sbin/nologin"
      OpenBSD: "/usr/sbin/nologin"
    usernames: "{{ users|dict2items|map(attribute='key')|list }}"
  block:
    - name: add luser
      with_items: "{{ lusers }}"
      user:
        name: "{{ item }}"
        shell: "{{ login_shell[ansible_distribution] }}"

    - name: getent passwd
      getent:
        database: passwd

    - name: disable luser
      with_items: "{{ usernames }}"
      when: (item not in lusers) and (item in getent_passwd)
      user:
        name: "{{ item }}"
        shell: "{{ nologin_shell[ansible_distribution] }}"

    - name: authorized_keys, exclusively managed by Ansible
      copy:
        dest: "/home/{{ item }}/.ssh/authorized_keys"
        content: "{{ users[item].authorized_keys }}"
      when: lusers_authorized_keys_exclusive
      with_items: "{{ lusers }}"

    - name: authorized_keys, shared management with Ansible
      authorized_key:
        user: "{{ item }}"
        key: "{{ users[item].authorized_keys }}"
      with_items: "{{ lusers }}"
      when: not lusers_authorized_keys_exclusive
