- set_fact:
    docker_service__root: "{{ docker_service__etc }}/{{ docker_service }}"

- name: "{{ docker_service__root }}"
  become: yes
  file:
    path: "{{ docker_service__root }}"
    state: directory

- name: "{{ docker_service__root }}/docker-compose.yml"
  become: yes
  template:
    dest: "{{ docker_service__root }}/docker-compose.yml"
    src: "{{ template }}"
  notify:
    - "docker-service: pull"
    - "docker-service: reload"
  register: docker_descriptor

- name: "/etc/systemd/system/{{ systemd_unit }}.service"
  become: yes
  copy:
    dest: "/etc/systemd/system/{{ systemd_unit }}.service"
    content: |
      [Unit]
      Description=Docker service: {{ docker_service }}
      After=network-online.target
      After=docker.service
      Requires=docker.service

      {% if docker_service__requires_mounts_for|default([])|length > 0 %}
      RequiresMountsFor=
      {%- for x in docker_service__requires_mounts_for|default([]) %}
      {{ x }}{% if not loop.last %} {% endif %}
      {% endfor %}

      {% endif %}

      [Service]
      WorkingDirectory={{ docker_service__etc }}/{{ docker_service }}/
      Type=oneshot
      RemainAfterExit=true
      ExecStartPre=/usr/bin/docker-compose pull
      ExecStart=/usr/bin/docker-compose up -d

      ExecStop=/usr/bin/docker-compose stop

      ExecReload=/usr/bin/docker-compose pull
      ExecReload=/usr/bin/docker-compose up -d

      [Install]
      WantedBy=multi-user.target
  notify:
    - "docker-service: pull"
    - "docker-service: reload"
  register: systemd_descriptor

- name: systemd daemon-reload
  become: yes
  systemd:
    daemon_reload: yes
  when: systemd_descriptor.changed

- set_fact:
    docker_service__reload: "{{ docker_service__reload + [systemd_unit] }}"
  when: (systemd_descriptor.changed or docker_descriptor.changed) and systemd_state == 'started'
