- hosts:
    - p2k16-production
    - p2k16-staging
  vars:
    docker_service: p2k16
    docker_service_root: "/etc/docker-service/{{ docker_service }}"
  tasks:
    - tags:
        - docker-service
      become: yes
      block:
        - name: "mkdir {{ docker_service_root }}"
          file:
            path: "{{ docker_service_root }}"
            state: directory

        - loop:
            - Caddyfile
          template:
            src: "{{ item }}"
            dest: "{{ docker_service_root }}/{{ item }}"
          notify:
            - "docker-service: pull"
            - "docker-service: reload"

    - import_role:
        name: docker-service
      tags:
        - docker-service
      vars:
        template: "docker-compose.yml.j2"
