- name: docker-compose pull
  become: yes
  listen: "docker-service: pull"
# https://github.com/ansible-collections/community.docker/issues/184
#  community.docker.docker_compose:
#    project_src: "{{ docker_service__etc }}/{{ docker_service }}"
#    pull: yes
  shell: docker-compose pull
  args:
    chdir: "{{ docker_service__root }}"

- name: Reload Docker Service
  listen: "docker-service: reload"
  become: yes
  loop: "{{ docker_service__reload }}"
  systemd:
    name: "{{ item }}"
    state: reloaded
