---
- name: super user accounts
  tags: users
  become: yes
  user:
    name: "{{ item.username }}"
    groups: sudo,libvirt,kvm,libvirt-qemu,systemd-journal
    append: yes
  with_items:
    - "{{ users }}"

- name: users' authorized_keys
  tags: users
  become: yes
  authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ item.authorized_keys }}"
  with_items:
    - "{{ users }}"
