---
- name: superuser accounts
  tags: superusers
  become: yes
  user:
    name: "{{ item.username }}"
    groups: sudo,systemd-journal
    append: yes
  with_items:
    - "{{ superusers }}"

- name: superuser authorized_keys
  tags: superusers
  become: yes
  authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ item.authorized_keys }}"
  with_items:
    - "{{ superusers }}"
