homeassistant:
  # Name of the location where Home Assistant is running
  name: Bitraf
  # Location required to calculate the time the sun rises and sets
  latitude: 59.914092
  longitude: 10.749151
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 108
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
  - platform: google_travel_time
    name: Evening Commute
    api_key: AIzaSyD5xOovfSWjIDehx2bhT9gxss7FJuoO99s
    origin: place_id:ChIJJ0JfiXluQUYRyQ9mkelkc8U
    destination: place_id:ChIJ44LZOGJuQUYRy7dqnoNNkSY
    options:
      mode: walking
  - platform: darksky
    #name: weather
    api_key: 8c9272a9c60254c19cb65c58f460a015
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - temperature
      - humidity
      - apparent_temperature
      - precip_probability
      - precip_intensity
      - wind_speed
      - pressure
      - wind_bearing
  - platform: mqtt
    state_topic: "bitraf/temperature/1"
    name: Temperature 1
    unit_of_measurement: "&deg;C"

switch:
  - platform: mqtt
    command_topic: "public/hydroponics-1/water/watercycle/-1"
    #payload_on: "-1"
    name: watercycle

# Text to speech
tts:
  platform: google

group: !include groups.yaml

# Example configuration.yml entry
light:
  - platform: mqtt
    command_topic: "public/hydroponics-1/lights-on"
    payload_on: "now"
    payload_off: "now"
    name: hydroponics_1

mqtt:
  broker: mqtt.bitraf.no

automation:
  - alias: hydroponics control on
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service: turn_on
        service_data:
          entity_id: switch.hydroponics_lights
    action: 
      service: light.turn_on
  - alias: hydroponics control off
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service: turn_off
        service_data:
          entity_id: switch.hydroponics_lights
    action:
      service: light.turn_off
  - alias: hydroponics water
    trigger:
      platform: event
      event_type: call_service
      event_data:
        #service: turn_on
        service_data:
          entity_id: switch.hydroponics_water
    action:
      service: switch.turn_on
      #entity_id: light.hyroponics_1


#device_tracker:
#  - platform: bluetooth_tracker
