---
- name: configure network interfaces
  tags: network
  become: yes
  copy:
    dest: /etc/network/interfaces
    content: |
      source /etc/network/interfaces.d/*

      auto lo
      iface lo inet loopback

- name: configure bitraf network interfaces
  tags: network
  become: yes
  copy:
    dest: /etc/network/interfaces.d/bitraf
    content: |
      #auto enp4s0f0
      #iface enp4s0f0 inet dhcp

      auto enp4s0f1
      iface enp4s0f1 inet static
              address 77.40.158.102
              netmask 255.255.255.224
              gateway 77.40.158.97

- name: disable ipv6 autoconf for enp4s0f1
  tags: network
  become: yes
  sysctl:
    name: net.ipv6.conf.enp4s0f1.autoconf
    value: 0
    state: present
    reload: yes

- name: configure name resolution
  tags: network
  become: yes
  copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 8.8.8.8
      nameserver 8.8.4.4
